# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        log:
            entity:
                class: AppBundle:Client
                property: nom
        in_memory:
            memory: ~
    encoders:
        AppBundle\Entity\Client: plaintext
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            
            provider: log
            form_login: 
                login_path: homepage
                check_path: checkDeBanque
                
            logout:
                path: logOut
                target: /log
        
    access_control:  
        - { path: ^/compte , roles: ROLE_USER }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
